# Generated by Django 3.0.5 on 2020-04-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200419_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
